name: linux

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Download and Install SDL2
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.3
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON