name: macosx

on: [push]

jobs:
  macosx-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Download and Install SDL2
      run: brew install sdl2 sdl2_image
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.3
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON